export const PATHS = {
  home: "/",
  products: "/products",
  s1: "/products/s1",
  s1x: "/products/s1x",
  s2: "/products/s2",
  ps1: "/products/ps1",
  gallery: "/gallery",
  about: "/about",
  technology: "about/technology",
  news: "/news",
  press: "/news/press",
  listen: "/listen",
  shows: "/listen/shows",
  appointment: "/listen/appointment",
  contact: "/contact",
  reserve: "/reserve",
  COMMENTS_API:
    "https://lpbj4kohdb.execute-api.us-west-2.amazonaws.com/api/contact-form",
};
